project:
  type: website
execute:
  freeze: auto

website:
  title: "Fabrice Rossi"
  site-url: https://fabrice-rossi.github.io/
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: blog/index.qmd
        text: Developer Diary
      - about.qmd
    right:
      - icon: rss
        href: blog/index.xml
  draft-mode: gone

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



